import type { Keyboard } from "../types";

export const keyboardEn: Keyboard = [
  [
    { content: "`", size: 96, type: "letter", opacity: true },
    { content: "1", size: 96, type: "letter" },
    { content: "2", size: 96, type: "letter" },
    { content: "3", size: 96, type: "letter" },
    { content: "4", size: 96, type: "letter" },
    { content: "5", size: 96, type: "letter" },
    { content: "6", size: 96, type: "letter" },
    { content: "7", size: 96, type: "letter" },
    { content: "8", size: 96, type: "letter" },
    { content: "9", size: 96, type: "letter" },
    { content: "0", size: 96, type: "letter" },
    { content: "-", size: 96, type: "letter" },
    { content: "=", size: 96, type: "letter", opacity: true },
    { content: "delete", size: 168, type: "text", align: "bottom-right" },
  ],

  [
    {
      content: "tab",
      size: 168,
      type: "text",
      opacity: true,
      align: "bottom-left",
    },
    { content: "q", size: 96, type: "letter" },
    { content: "w", size: 96, type: "letter" },
    { content: "e", size: 96, type: "letter" },
    { content: "r", size: 96, type: "letter" },
    { content: "t", size: 96, type: "letter" },
    { content: "y", size: 96, type: "letter" },
    { content: "u", size: 96, type: "letter" },
    { content: "i", size: 96, type: "letter" },
    { content: "o", size: 96, type: "letter" },
    { content: "p", size: 96, type: "letter" },
    { content: "[", size: 96, type: "letter", opacity: true },
    { content: "]", size: 96, type: "letter", opacity: true },
    { content: "\\", size: 96, type: "letter", opacity: true },
  ],

  [
    {
      content: ["·", "capslock"],
      size: 192,
      type: "text",
      opacity: true,
      align: "left",
    },
    { content: "a", size: 96, type: "letter" },
    { content: "s", size: 96, type: "letter" },
    { content: "d", size: 96, type: "letter" },
    { content: "f", size: 96, type: "letter" },
    { content: "g", size: 96, type: "letter" },
    { content: "h", size: 96, type: "letter" },
    { content: "j", size: 96, type: "letter" },
    { content: "k", size: 96, type: "letter" },
    { content: "l", size: 96, type: "letter" },
    { content: ";", size: 96, type: "letter", opacity: true },
    { content: "'", size: 96, type: "letter" },
    { content: "return", size: 180, type: "text", align: "bottom-right" },
  ],

  [
    { content: "shift", size: 240, type: "text", align: "bottom-left" },
    { content: "z", size: 96, type: "letter" },
    { content: "x", size: 96, type: "letter" },
    { content: "c", size: 96, type: "letter" },
    { content: "v", size: 96, type: "letter" },
    { content: "b", size: 96, type: "letter" },
    { content: "n", size: 96, type: "letter" },
    { content: "m", size: 96, type: "letter" },
    { content: ",", size: 96, type: "letter" },
    { content: ".", size: 96, type: "letter" },
    { content: "/", size: 96, type: "letter", opacity: true },
    { content: "shift", size: 240, type: "text", align: "bottom-right" },
  ],

  [
    {
      content: "fn",
      size: 96,
      type: "text",
      align: "bottom-right",
      opacity: true,
    },
    {
      content: ["⌃", "сontrol"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌥", "option"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌘", "command"],
      size: 144,
      type: "text",
      align: "right",
      opacity: true,
    },
    { content: " ", size: 504, type: "text" },
    {
      content: ["⌘", "command"],
      size: 144,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌥", "option"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    { content: "◀", size: 96, type: "text", align: "center", opacity: true },
    {
      content: ["▲", "▼"],
      size: 96,
      type: "text",
      align: "center",
      opacity: true,
      extraClass: "keyboard__key_divider",
    },
    { content: "▶", size: 96, type: "text", align: "center", opacity: true },
  ],
];
