import type { Keyboard } from "../types";

export const keyboardRu: Keyboard = [
  [
    { content: "ё", size: 96, type: "letter" },
    { content: "1", size: 96, type: "letter" },
    { content: "2", size: 96, type: "letter" },
    { content: "3", size: 96, type: "letter" },
    { content: "4", size: 96, type: "letter" },
    { content: "5", size: 96, type: "letter" },
    { content: "6", size: 96, type: "letter" },
    { content: "7", size: 96, type: "letter" },
    { content: "8", size: 96, type: "letter" },
    { content: "9", size: 96, type: "letter" },
    { content: "0", size: 96, type: "letter" },
    { content: "-", size: 96, type: "letter" },
    { content: "=", size: 96, type: "letter", opacity: true },
    { content: "delete", size: 168, type: "text", align: "bottom-right" },
  ],

  [
    {
      content: "tab",
      size: 168,
      type: "text",
      opacity: true,
      align: "bottom-left",
    },
    { content: "й", size: 96, type: "letter" },
    { content: "ц", size: 96, type: "letter" },
    { content: "у", size: 96, type: "letter" },
    { content: "к", size: 96, type: "letter" },
    { content: "е", size: 96, type: "letter" },
    { content: "н", size: 96, type: "letter" },
    { content: "г", size: 96, type: "letter" },
    { content: "ш", size: 96, type: "letter" },
    { content: "щ", size: 96, type: "letter" },
    { content: "з", size: 96, type: "letter" },
    { content: "х", size: 96, type: "letter" },
    { content: "ъ", size: 96, type: "letter" },
    { content: "\\", size: 96, type: "letter", opacity: true },
  ],

  [
    {
      content: ["·", "capslock"],
      size: 192,
      type: "text",
      opacity: true,
      align: "left",
    },
    { content: "ф", size: 96, type: "letter" },
    { content: "ы", size: 96, type: "letter" },
    { content: "в", size: 96, type: "letter" },
    { content: "а", size: 96, type: "letter" },
    { content: "п", size: 96, type: "letter" },
    { content: "р", size: 96, type: "letter" },
    { content: "о", size: 96, type: "letter" },
    { content: "л", size: 96, type: "letter" },
    { content: "д", size: 96, type: "letter" },
    { content: "ж", size: 96, type: "letter" },
    { content: "э", size: 96, type: "letter" },
    { content: "return", size: 180, type: "text", align: "bottom-right" },
  ],

  [
    { content: "shift", size: 240, type: "text", align: "bottom-left" },
    { content: "я", size: 96, type: "letter" },
    { content: "ч", size: 96, type: "letter" },
    { content: "с", size: 96, type: "letter" },
    { content: "м", size: 96, type: "letter" },
    { content: "и", size: 96, type: "letter" },
    { content: "т", size: 96, type: "letter" },
    { content: "ь", size: 96, type: "letter" },
    { content: "б", size: 96, type: "letter" },
    { content: "ю", size: 96, type: "letter" },
    { content: ".", size: 96, type: "letter" },
    { content: "shift", size: 240, type: "text", align: "bottom-right" },
  ],

  [
    {
      content: "fn",
      size: 96,
      type: "text",
      align: "bottom-right",
      opacity: true,
    },
    {
      content: ["⌃", "сontrol"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌥", "option"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌘", "command"],
      size: 144,
      type: "text",
      align: "right",
      opacity: true,
    },
    { content: " ", size: 504, type: "text" },
    {
      content: ["⌘", "command"],
      size: 144,
      type: "text",
      align: "right",
      opacity: true,
    },
    {
      content: ["⌥", "option"],
      size: 96,
      type: "text",
      align: "right",
      opacity: true,
    },
    { content: "◀", size: 96, type: "text", align: "center", opacity: true },
    {
      content: ["▲", "▼"],
      size: 96,
      type: "text",
      align: "center",
      opacity: true,
      extraClass: "keyboard__key_divider",
    },
    { content: "▶", size: 96, type: "text", align: "center", opacity: true },
  ],
];
